namespace Minsk.CodeAnalysis.Syntax
{
    public enum SyntaxKind
    {
        // Tokens
        BadToken,
        ColonToken,
        CommaToken,
        EndOfFileToken,
        WhitespaceToken,
        NumberToken,
        PlusToken,
        MinusToken,
        StarToken,
        SlashToken,
        BangToken,
        AmpersandToken,
        AmpersandAmpersandToken,
        EqualsToken,
        EqualsEqualsToken,
        BangEqualsToken,
        PipePipeToken,
        OpenParenthesisToken,
        CloseParenthesisToken,
        IdentifierToken,
        OpenBraceToken,
        CloseBraceToken,
        LessToken,
        LessOrEqualsToken,
        GreaterToken,
        GreaterOrEqualsToken,
        TildeToken,
        HatToken,
        PipeToken,
        // Keywords
        DoKeyword,
        FalseKeyword,
        FunctionKeyword,
        TrueKeyword,
        LetKeyword,
        VarKeyword,
        IfKeyword,
        ElseKeyword,
        WhileKeyword,
        ForKeyword,
        StringToken,
        ToKeyword,

        // Expressions
        CallExpression,
        LiteralExpression,
        UnaryExpression,
        BinaryExpression,
        ParenthesizedExpression,
        NameExpression,
        AssignmentExpression,

        //unit
        CompilationUnit,
        ElseClause,
        TypeClause,
        // Statements
        DoWhileStatement,
        ExpressionStatement,
        BlockStatement,
        VariableDeclaration,
        IfStatement,
        WhileStatement,
        ForStatement,
        FunctionDeclaration,
        GlobalStatement,
        Parameter,
    }
}

